# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Crt1-PHLxUobjp2le9Mu1zi64cjoWdB
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['axes.grid'] = True
plt.rcParams['grid.alpha'] = 0.3

url = "avengers.csv"
df = pd.read_csv(url, encoding="latin1")
print("Sətir sayı:", df.shape[0], "| Sütun sayı:", df.shape[1])
df.head()

death_cols = ["Death1", "Death2", "Death3", "Death4", "Death5"]
df["DeathCount"] = df[death_cols].apply(lambda row: (row == "YES").sum(), axis=1)
df["EverDied"] = df["DeathCount"] > 0

main_cols = ["Name/Alias", "Appearances", "Current?", "Gender", "Year",
             "Years since joining", "Honorary", "DeathCount", "EverDied"]
clean = df[main_cols].copy()
clean.columns = ["Name", "Appearances", "Current", "Gender", "YearJoined",
                  "YearsSinceJoining", "Honorary", "DeathCount", "EverDied"]

total = len(clean)
died = clean["EverDied"].sum()
print(f"Ümumi personaj sayı: {total}")
print(f"Ən azı 1 dəfə 'ölmüş': {died} ({died/total*100:.1f}%)")
print(f"Maksimum ölüm sayı: {clean['DeathCount'].max()}")
print(clean["Gender"].value_counts())

top10 = clean.sort_values("Appearances", ascending=False).head(10)
fig, ax = plt.subplots()
ax.barh(top10["Name"][::-1], top10["Appearances"][::-1], color="#4c72b0")
ax.set_xlabel("Görünüş sayı")
ax.set_title("Ən çox görünən 10 Avengers personajı")
ax.xaxis.set_major_formatter(mticker.StrMethodFormatter('{x:,.0f}'))
plt.tight_layout()
plt.show()

fig, ax = plt.subplots()
ax.scatter(clean["DeathCount"], clean["Appearances"], alpha=0.6, color="#c44e52")
ax.set_xlabel("Ölüm sayı")
ax.set_ylabel("Görünüş sayı")
ax.set_title("Ölüm sayı vs Populyarlıq")
plt.tight_layout()
plt.show()
print("Korrelyasiya:", clean["DeathCount"].corr(clean["Appearances"]))

by_year = clean.groupby("YearJoined").size()
fig, ax = plt.subplots()
ax.plot(by_year.index, by_year.values, marker="o", color="#55a868")
ax.set_xlabel("İl")
ax.set_ylabel("Yeni üzv sayı")
ax.set_title("İllər üzrə qoşulma tempi")
plt.tight_layout()
plt.show()

gender_death = clean.groupby("Gender")["EverDied"].mean() * 100
fig, ax = plt.subplots()
ax.bar(gender_death.index, gender_death.values, color=["#4c72b0", "#dd8452"])
ax.set_ylabel("Ölüm faizi (%)")
ax.set_title("Cins üzrə ölüm faizi")
for i, v in enumerate(gender_death.values):
    ax.text(i, v + 1, f"{v:.1f}%", ha="center")
plt.tight_layout()
plt.show()