# -*- coding: utf-8 -*-
"""FIFAPlayerDATASET.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JWJQu2J9-gDwiF11URr-GbxnukKnT9pM
"""

import pandas as pd
import numpy as np

df = pd.read_csv('fifa.csv')
max_rating = df['Overall_Rating'].max()
mean_age = df['Age'].mean()

print(f"Ən yüksək reytinq: {max_rating}")
print(f"Oyunçuların orta yaşı: {mean_age:.1f}")

print("\n" + "="*40 + "\n")

print("Mövqelərə görə orta reytinq:")
print(df.groupby('Position')['Overall_Rating'].mean().round(1))

print("--- ƏN YÜKSƏK REYTİNQLİ 5 OYUNÇU ---")
top_players = df.nlargest(5, 'Overall_Rating')[['Name', 'Country', 'Position', 'Overall_Rating']]
print(top_players)

print("\n" + "="*50 + "\n")

print("--- EN YÜKSƏK YAŞA SAHİB (ƏN YAŞLI) OYUNÇULAR ---")
oldest_players = df.nlargest(5, 'Age')[['Name', 'Team', 'Age', 'Overall_Rating']]
print(oldest_players)


azad_agentler = df[df['Duration'] == 'Free']

print("--- EN YAXŞI 5 AZAD AGENT ---")
print(azad_agentler[['Name', 'Position', 'Potential', 'Duration']].head(5))


kontrakt_2026 = df[df['Duration'].str.endswith('2026', na=False)]

en_yaxsi_2026 = kontrakt_2026.nlargest(10, 'Overall_Rating')

print("=" * 65)
print("       2026-CI İLDƏ KONTRAKTI BİTƏN ƏN YAXŞI 10 OYUNÇU")
print("=" * 65)
print(en_yaxsi_2026[['Name', 'Team', 'Position', 'Overall_Rating', 'Duration']].to_string(index=False))
print("=" * 65)

komanda_budcesi = df.groupby('Team')['Value € M'].agg(
    Toplam_Dəyər_M=('sum'),
    Orta_Oyunçu_Dəyəri_M=('mean'),
    Oyunçu_Sayı=('count')
).round(1)

en_bahali_klublar = komanda_budcesi.nlargest(10, 'Toplam_Dəyər_M')
print("=" * 75)
print("          FİFA DATASETİNDƏ ƏN YÜKSƏK HEYƏT DƏYƏRİNƏ SAHİB 10 KLUB")
print("=" * 75)
print(en_bahali_klublar.reset_index().to_string(index=False))
print("=" * 75)



olkeler = df.groupby('Country').agg(
    Oyuncu_Sayi=('Name', 'count'),
    Orta_Reytinq=('Overall_Rating', 'mean')
)
guclu_olkeler = olkeler[olkeler['Oyuncu_Sayi'] >= 30]
top_countries = guclu_olkeler.nlargest(10, 'Orta_Reytinq')
print("=" * 60)
print("          ƏN YÜKSƏK KEYFİYYƏTLİ FUTBOL ÖLKƏLƏRİ (Top 10)")
print("=" * 60)
print(top_countries.round(1).reset_index().to_string(index=False))
print("=" * 60)



veteranlar = df[df['Age'] > 34]
en_yaxsi_veteranlar = veteranlar.nlargest(5, 'Overall_Rating')
print("=" * 65)
print("            DATADAKI ƏN GÜCLÜ 5 VETERAN OYUNÇU (Age > 34)")
print("=" * 65)
print(en_yaxsi_veteranlar[['Name', 'Team', 'Age', 'Overall_Rating', 'Duration']].to_string(index=False))
print("=" * 65)

df['Growth'] = df['Potential'] - df['Overall_Rating']
en_potensialli_gencler = df[df['Age'] < 22].nlargest(10, 'Growth')
print("=" * 75)
print("          KARYERA REJİMİ ÜÇÜN ƏN ÇOX İNKİŞAF EDƏCƏK GƏNC TALANTLAR")
print("=" * 75)
print(en_potensialli_gencler[['Name', 'Team', 'Age', 'Overall_Rating', 'Potential', 'Growth']].to_string(index=False))
print("=" * 75)
